---
- name: Converge
  hosts: all
  tasks:
    - name: "Test yum_config repo config"
      become: true
      tripleo.repos.yum_config:
        type: repo
        name: appstream
        enabled: true
      tags:
        # TODO: fix yum_config to correctly report changed state and uncomment
        # the line below which disables molecule idemptotence test.
        - molecule-idempotence-notest
      when: ansible_distribution_major_version is version(8, '>=')

    - name: "Test yum_config global config"
      become: true
      tripleo.repos.yum_config:
        type: global
        file_path: /etc/dnf/dnf.conf
        set_options:
          skip_if_unavailable: "False"
          keepcache: "0"
      tags:
        # TODO: fix yum_config to correctly report changed state and uncomment
        # the line below which disables molecule idemptotence test.
        - molecule-idempotence-notest

    - name: "Check get_hash"
      tripleo.repos.get_hash:
        release: master

    - name: "Check get_hash with invalid url"
      tripleo.repos.get_hash:
        release: master
        dlrn_url: 'https://httpbin.org/status/404'
      register: result
      failed_when: result is success

    - name: "Test yum_config enable-compose-repos"
      become: true
      tripleo.repos.yum_config:
        type: enable-compose-repos
        compose_url: https://composes.centos.org/latest-CentOS-Stream-8/compose/
        centos_release: centos-stream-8
        variants:
          - AppStream
          - BaseOS
        disable_repos:
           - /etc/yum.repos.d/CentOS-Stream-AppStream.repo
           - /etc/yum.repos.d/CentOS-Stream-BaseOS.repo
      tags:
        - molecule-idempotence-notest
