---
  - name: "Search for {{ item }} repos"
    find:
      paths: "/etc/yum.repos.d"
      file_type: file
      use_regex: yes
      patterns:
       - "^CentOS-Stream.*{{ item }}.*.repo$"
      excludes:
       - "CentOS-Stream-{{ item }}.repo"
    register: compose_repos
    failed_when: compose_repos.files|length != 1

  - name: Validate repo file configuration
    include_tasks: assert_ini_key_value.yml
    with_items:
     - name: "{{ item }}"
       path: "{{ compose_repos.files[0].path }}"
       section: "{{ item|lower }}"
       key: enabled
       value: "1"
     - name: "{{ item }}"
       path: "/etc/yum.repos.d/CentOS-Stream-{{ item }}.repo"
       section: "{{ item|lower }}"
       key: enabled
       value: "0"
